cloud_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('leagues.urls', namespace='leagues')),
    url(r'cloud_roni/', include('CloudRoni.urls', namespace='cloud_roni')),
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^csv/', include('csv_upload.urls', namespace='csv_upload')),
    url(r'^draft/', include('drafts.urls', namespace='drafts')),    
]

drafts/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

from . import views

app_name = 'drafts'
urlpatterns = [
    url(r'^start_draft/$', views.start_draft, name='start_draft'),
    url(r'^draft_player/$', views.draft_player, name='draft_player'),
    url(r'^end_draft/$', views.end_draft, name='end_draft'),
    url(r'^auto_draft/$', views.auto_draft, name='auto_draft'),
    url(r'^draft_results/$', views.draft_results, name='draft_results'),
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

app_name = 'users'
urlpatterns = [
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^(?P<user_id>[0-9]+)/account/$', views.update_account, name='account'),
    url(r'^update_phone_number/$', views.create_or_update_phone_number, name='create_or_update_phone_number'),
]

drafts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime

from django.db import models
from django.utils import timezone
from django.db.models import Sum, F
from django.contrib.auth.models import User
from CloudRoni.models import Team, UserPlayer
from leagues.models import League

# Create your models here.
class Draft(models.Model):
    league = models.ForeignKey(League)
    started_date = models.DateTimeField('started')
    current_team = models.ForeignKey(Team, null=True, blank=True)
    next_team = models.IntegerField(null=True, blank=True)
    end_turn_timer = models.DateTimeField('timer')

class Drafter(models.Model):
    team = models.OneToOneField(Team)
    position = models.IntegerField()
    league = models.ForeignKey(League)
    draft = models.ForeignKey(Draft)

drafts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import Http404, HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, render, redirect, render_to_response
from django.core.exceptions import ObjectDoesNotExist
from django.template import loader, RequestContext
from django.urls import reverse
from django.shortcuts import render
from CloudRoni.models import Team, UserPlayer
from drafts.models import Draft, Drafter
from django.utils import timezone
from leagues.forms import LeagueForm
from django.views.decorators.csrf import csrf_exempt
from leagues.models import League
import datetime
import random

import pdb
# Create your views here.
def start_draft(request):
    league = request.user.league

    teams = Team.objects.filter(league=league)
    players = UserPlayer.objects.filter(league=league)

    if teams.count() < 3 or not players.count() > 0:
        form = LeagueForm(request.POST or None, instance=request.user.league)
        confirmation = 'You need more players/teams to start a draft'
        return render(request, 'leagues/league_management.html', {'form': form, 'confirmation': confirmation})

    try:
        draft = Draft.objects.get(league=league)
        
        context = {
            'teams_list': teams,
            'draft': draft,
            'initial': Drafter.objects.get(league=league, team=draft.current_team),
            'players_list': UserPlayer.objects.filter(league=league),
        }

    except ObjectDoesNotExist:
        draft = Draft(league=league,
                        started_date=timezone.now(),
                        end_turn_timer=timezone.now() + datetime.timedelta(minutes=3)
                        )
        draft.save()
        position_arr = random.sample(xrange(1,teams.count()+1), teams.count())
        for team in teams:
            drafter = Drafter(team=team,
                                position=position_arr.pop(),
                                league=league,
                                draft=draft)
            drafter.save()

        draft.current_team = Drafter.objects.get(league=league, position=1).team
        draft.next_team = 2
        draft.save()
        
        league.drafted = True
        league.save()

        context = {
            'teams_list': teams,
            'draft': draft,
            'initial': Drafter.objects.get(league=league, position=1),
            'players_list': UserPlayer.objects.filter(league=league),
        }
    
    return render(request, 'drafts/draft_dashboard.html', context)

@csrf_exempt
def auto_draft(request):
    league = request.user.league
    team = Team.objects.get(id=int(request.POST.get('team_id')))
    player = UserPlayer.objects.filter(league=league, player_team=None).first()

    response = finalize_draft_pick(team, player, league)

    return response

@csrf_exempt
def draft_player(request):
    league = request.user.league
    team = Team.objects.get(id=int(request.POST.get('team_id')))
    player = UserPlayer.objects.get(id=int(request.POST.get('player_id')))

    response = finalize_draft_pick(team, player, league)
    return response

@csrf_exempt
def end_draft(request):
    Draft.objects.get(league=request.user.league).delete()
    return JsonResponse({'url': reverse('cloud_roni:index')})

def draft_results(request):
    league = League.objects.get(participants=request.user)
    if not league.drafted:
        return HttpResponseRedirect(reverse('cloud_roni:index'))

    teams = Team.objects.filter(league=league)

    return render(request, 'drafts/draft_results.html', {'team_list': teams})

def finalize_draft_pick(team, player, league):
    player.player_team = player.drafted_team = team
    player.drafted = True
    player.save()

    teams = Team.objects.filter(league=league)
    if league.is_players_available():
        return JsonResponse({
            'ended': True,
            'url': reverse('drafts:end_draft'),
        })

    draft = Draft.objects.get(league=league)
    try:
        position = draft.next_team
        current_team = Drafter.objects.get(league=league, position=position)
        draft.next_team += 1
    except ObjectDoesNotExist:
        draft.next_team = 2
        current_team = Drafter.objects.get(league=league, position=1)

    draft.current_team = current_team.team
    draft.end_turn_timer = timezone.now() + datetime.timedelta(minutes=3)
    draft.save()

    try:
        player_list = []
        for solo_player in UserPlayer.objects.filter(player_team=current_team.team):
            player_list.append(str(solo_player))
    except:
        player_list = {}

    teams_player_list = {}
    for individual_team in teams:
        teams_player_list[str(individual_team)] = []
        for team_player in individual_team.get_player_set():
            teams_player_list[str(individual_team)].append(str(team_player))

    return JsonResponse({
        'current_team_name': str(current_team.team),
        'current_team_id': current_team.team.id,
        'end_time': draft.end_turn_timer,
        'current_team_players': player_list,
        'drafted_player_id': player.id,
        'teams_player_list': teams_player_list,
    })

drafts/templates/drafts/draft_dashboard.html
{% extends 'base.html' %}
{% load static %}
{% load fontawesome %}

{% block content%}
<script src="{% static 'drafts/js/drafts.js' %}"></script>
<link rel="stylesheet" href="{% static 'drafts/css/drafts.css' %}">
<link rel="stylesheet" href="{% static 'drafts/css/jquery.countdown.css' %}"> 
<script type="text/javascript" src="{% static 'drafts/js/jquery.plugin.js' %}"></script> 
<script type="text/javascript" src="{% static 'drafts/js/jquery.countdown.js' %}"></script>
<script type="text/javascript">
    $(document).ready(function() {
        var endTimer = new Date("{{ draft.end_turn_timer.isoformat }}");
        endTimer = new Date(endTimer.getTime());
        $('#countdown').countdown({
            until: endTimer,
            format: 'MS',
            compact: true,
            onTick: autoDraft,
            description: 'Draft Timer',
        });

        $('.draft-button').on('click', function() {
            draftPlayer("{% url 'drafts:draft_player' %}", $(this).data('player-id'), $('#current-draftee').data('team-id'));
        });
    });
</script>

<div id='draft-dashboard'>
    <div id='current-draftee' data-team-id='{{initial.team.id}}' class='three-column'>
        <h1 id='current-team-header'>Current Drafting Team</h1>
        <div class='inner-details'>
            <h3>Team: <span id='drafting-team-name' style='font-weight: normal'>{{ initial.team }}</span></h3>
            <ol id='drafting-team'>
                {% for player in initial.team.get_player_set %}
                    <li>{{ player }} - {{ player.usage }}</li>
                {% endfor %}
            </ol>
        </div>
    </div>
    
    <div id="available-players" class='three-column'>
        <div id='countdown'>
        </div>
        <div class='header'>
            <h1 id='available-players-header'>Available Players</h1>
        </div>
        <ol>
            {% for player in players_list %}
                <li class='avail-player-li'>
                    <span class='avail-player-name'>{{ player }}</span>
                    {% if not player.player_team %}
                        <button class='draft-button' data-player-id='{{ player.id }}'>Draft</button>
                    {% endif %}
                </li>
            {% endfor %}
        </ol>
    </div>
    
    <div id="other-teams" class='three-column'>
        <h1 id='other-teams-header'>Other Teams</h1>
        {% for team in teams_list %}
            {% if team != initial.team %}
                <div class='waiting-team'>
                    <h4>{{ team.drafter.position }}. {{ team }}</h4>
                    <ol>
                        {% for player in team.get_player_set %}
                            <li>{{ player }} - {{ player.usage }}</li>
                        {% endfor %}
                    </ol>
                </div>
                <div class='five-px-spacer'></div>
            {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock content %}

drafts/templates/drafts/draft_results.html
{% extends 'base.html' %}
{% load static %}
{% load fontawesome %}

{% block content%}
<script src="{% static 'drafts/js/drafts.js' %}"></script>
<link rel="stylesheet" href="{% static 'drafts/css/drafts.css' %}">

<div id="draft-results-container">
    <h1 id='draft-results-header'>Draft Results</h1>
    {% for team in team_list %}
        <div class='drafted-team'>
            <h4>{{ forloop.counter }}. {{ team }}</h4>
            <ol>
                {% for player in team.get_drafted_players %}
                    <li>{{ player }} - {{ player.usage }}</li>
                {% endfor %}
            </ol>
        </div>
    {% endfor %}
</div>

{% endblock content %}