CloudRoni/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

from . import views

app_name = 'cloud_roni'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    # ex: CloudRoni/5/team
    url(r'^(?P<pk>[0-9]+)/team/$', views.TeamView.as_view(), name='team'),
     # ex: CloudRoni/34/players/2/
    url(r'^(?P<team_id>[0-9]+)/players/(?P<player_id>[0-9]+)/$', views.players, name='players'),
    # ex: CloudRoni/2/create_player
    url(r'^(?P<team_id>[0-9]+)/create_player/$', views.create_player, name='create_player'),
    # ex: CloudRoni/create_team
    url(r'^create_team/$', views.create_team, name='create_team'),
    # ed: CloudRoni/update_player
    url(r'^(?P<player_id>[0-9]+)/update_player/$', views.update_player, name='update_player'),
    # ex: CloudRoni/55/delete_player
    url(r'^(?P<player_id>[0-9]+)/delete_player/$', views.delete_player, name='delete_player'),
    # ex: CloudRoni/55/add_point
    url(r'^(?P<player_id>[0-9]+)/add_point/$', views.add_point, name='add_point'),
    url(r'^players/$', views.PlayersView.as_view(), name='all_players'),
    url(r'^(?P<team_id>[0-9]+)/trade/$', views.place_trade, name='place_trade'),
    url(r'^trades/$', views.TradesView.as_view(), name='my_trades'),
    url(r'^complete_trade/$', views.complete_trade, name='complete_trade'),
    url(r'^rules/$', views.rules, name='rules'),
]

cloud_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('leagues.urls', namespace='leagues')),
    url(r'cloud_roni/', include('CloudRoni.urls', namespace='cloud_roni')),
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^csv/', include('csv_upload.urls', namespace='csv_upload')),
    url(r'^draft/', include('drafts.urls', namespace='drafts')),    
]

drafts/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

from . import views

app_name = 'drafts'
urlpatterns = [
    url(r'^start_draft/$', views.start_draft, name='start_draft'),
    url(r'^draft_player/$', views.draft_player, name='draft_player'),
    url(r'^end_draft/$', views.end_draft, name='end_draft'),
    url(r'^auto_draft/$', views.auto_draft, name='auto_draft'),
    url(r'^draft_results/$', views.draft_results, name='draft_results'),
]

leagues/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

from . import views

app_name = 'league'
urlpatterns = [
    url(r'^$', views.home_page, name='home_page'),
    url(r'^create_league/$', views.create_league, name='create_league'),
    url(r'^leagues/$', views.LeaguesListView.as_view(), name='leagues_index'),
    url(r'^join_league/$', views.join_league, name='join_league'),
    url(r'^manage_league/$', views.manage_league, name='manage_league'),
    url(r'^start_new_season/$', views.start_new_season, name='start_new_season'),
    url(r'^terminate_season/$', views.terminate_season, name='terminate_season'),
    url(r'^past_seasons/$', views.PastSeasonListView.as_view(), name='past_seasons'),
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

app_name = 'users'
urlpatterns = [
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^(?P<user_id>[0-9]+)/account/$', views.update_account, name='account'),
    url(r'^update_phone_number/$', views.create_or_update_phone_number, name='create_or_update_phone_number'),
]

CloudRoni/models.py
from __future__ import unicode_literals

import datetime

from django.db import models
from django.utils import timezone
from django.db.models import Sum, F
from django.contrib.auth.models import User
from leagues.models import League

import pdb

# Create your models here.
class Team(models.Model):
    team_name = models.CharField(max_length=200)
    created_date = models.DateTimeField('date published')
    team_owner = models.ForeignKey(User)
    team_points = models.IntegerField(default=0)
    league = models.ForeignKey(League)

    def __str__(self):
        return self.team_name

    def players_present(self):
        return UserPlayer.objects.filter(player_team=self).count() > 0

    def get_player_set(self):
        return UserPlayer.objects.filter(player_team=self)

    def get_drafted_players(self):
        return UserPlayer.objects.filter(drafted_team=self, drafted=True)

    def filter_team_points(self):
        players = UserPlayer.objects.filter(player_team=self)
        return players.aggregate(Sum('points_scored')).get('points_scored__sum', 0)

    def was_created_recently(self):
        return self.created_date <= timezone.now() - datetime.timedelta(days=1)

    def get_past_points(self):
        return Point.objects.filter(team=str(self), created__lte=datetime.datetime.today(), created__gt=datetime.datetime.today()-datetime.timedelta(days=7))

class UserPlayer(models.Model):
    HEAVY_USE = 'HU'
    MODERATE_USE = 'MU'
    LIGHT_USE = 'LU'
    NOT_USING = 'NU'
    USAGE_CHOICES = (
        (HEAVY_USE, 'Heavy Use'),
        (MODERATE_USE, 'Moderate Use'),
        (LIGHT_USE, 'Light Use'),
        (NOT_USING, 'Not Using'),
    )
    player_team = models.ForeignKey(Team,
                                    on_delete=models.SET_NULL,
                                    null=True)
    player_first_name = models.CharField(max_length=20)
    player_last_name = models.CharField(max_length=20)
    points_scored = models.IntegerField(default=0)
    usage = models.CharField(
        max_length=2,
        choices=USAGE_CHOICES,
        default=NOT_USING,)
    league = models.ForeignKey(League)
    drafted_team = models.ForeignKey(Team, related_name = "drafted_team", null=True, blank=True)
    drafted = models.BooleanField(default=False)

    def __str__(self):
        return self.player_first_name + ' ' + self.player_last_name

class Point(models.Model):
    ONE = 1
    MINUS_ONE = -1
    FIVE = 5
    POINT_CHOICES = (
        (ONE, "+1"),
        (MINUS_ONE, "-1"),
        (FIVE, "+5"),
    )
    player = models.ForeignKey(UserPlayer,
                              on_delete=models.CASCADE)
    point = models.IntegerField(
        choices=POINT_CHOICES,
        default=0)
    note = models.TextField(max_length=200)
    point_owner = models.ForeignKey(User)
    team = models.TextField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return str(self.point)

class Trade(models.Model):
    ACCEPTED = 1
    DECLINED = -1
    PENDING = 0
    OUTCOME_CHOICES = (
        (ACCEPTED, "Accepted"),
        (DECLINED, "Declined"),
        (PENDING, "Pending"),
    )
    proposing_team = models.ForeignKey(Team, related_name = "proposing_team")
    receiving_team = models.ForeignKey(Team, related_name = "receiving_team")
    is_completed = models.BooleanField(default=False)
    outcome = models.CharField(
        choices=OUTCOME_CHOICES,
        max_length=10,
        default="Pending")
    created_date = models.DateTimeField()
    proposing_team_players = models.ManyToManyField(UserPlayer, related_name = "proposing_team_players")
    receiving_team_players = models.ManyToManyField(UserPlayer, related_name = "receiving_team_players")
    
    def __str__(self):
        return self.proposing_team.team_name + " -> " + self.receiving_team.team_name

    def update_outcome(self, outcome):
        if(outcome == 'accept'):
            self.outcome = "Accepted"

            #transfer players to proposing team
            proposing_queryset = self.receiving_team_players.all()
            proposing_queryset.update(player_team=self.proposing_team)
            for player in proposing_queryset:
                player.save()

            #transfer players to receiving team
            receiving_queryset = self.proposing_team_players.all()
            receiving_queryset.update(player_team=self.receiving_team)
            for player in receiving_queryset:
                player.save()
        else:
            self.outcome = "Declined"

        self.is_completed = True
        self.save()

CloudRoni/forms.py
from django import forms
from CloudRoni.models import UserPlayer, Team, Point
from django.forms import ModelForm
from leagues.models import League

import pdb

CHOICES=[('HU', 'Heavy Usage'),
         ('MU', 'Moderate Usage'),
         ('LU', 'Light Usage'),
         ('NU', 'Not Using'),]

class UserPlayerForm(ModelForm):
	class Meta:
		model = UserPlayer
		exclude = ['player_team', 'points_scored', 'league']
		
class TeamForm(ModelForm):
    class Meta:
        model = Team
        exclude = ['created_date', 'team_points', 'league']

    def __init__(self, user, *args, **kwargs):
        super(TeamForm, self).__init__(*args, **kwargs)
        league = League.objects.get(participants=user)
        self.fields['team_owner'].queryset = league.participants.all()
        
class PointForm(ModelForm):
    class Meta:
        model = Point
        exclude = ['player', 'point_owner', 'team']

CloudRoni/views.py
from django.http import Http404, HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, render, redirect, render_to_response
from django.core.exceptions import ObjectDoesNotExist
from django.template import loader, RequestContext
from django.urls import reverse
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.contrib.auth.models import User
from users.models import PhoneNumber
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from leagues.models import League

from twilio.rest import Client


from CloudRoni.models import Team, UserPlayer, Point, Trade
from CloudRoni.forms import UserPlayerForm, TeamForm, PointForm

import pdb

class IndexView(generic.ListView):
	template_name = 'teams/index.html'
	context_object_name = 'teams_list'

	def get_queryset(self):
		"""Return all teams ordered by team_points"""
		league = League.objects.filter(participants=self.request.user)
		return Team.objects.filter(league=league).order_by('-team_points').reverse()

class PlayersView(generic.ListView):
	template_name = 'players/all_players.html'
	context_object_name = 'players_list'

	def get_queryset(self):
		query = self.request.GET.get('q')
		league = League.objects.get(participants=self.request.user)
		teams = Team.objects.filter(league=league)
		if query:
			result = (UserPlayer.objects.filter(league=league).filter(player_first_name=query) |
				UserPlayer.objects.filter(league=league).filter(player_last_name=query))
		else:
			result = UserPlayer.objects.filter(league=league)

		return result

class TeamView(generic.DetailView):
	model = Team
	template_name = 'teams/detail.html'

class TradesView(generic.ListView):
	template_name = 'teams/trades_index.html'
	context_object_name = 'trade_list'

	def get_queryset(self):
		try:
			team = Team.objects.get(team_owner=self.request.user)
			result = Trade.objects.filter(receiving_team=team) | Trade.objects.filter(proposing_team=team)
		except ObjectDoesNotExist:
			result = None
		return result

@login_required
def players(request, team_id, player_id):
	player = get_object_or_404(UserPlayer, pk=player_id)
	team = get_object_or_404(Team, pk=team_id)
	form_class = PointForm

	context = {
		'player': player,
		'team': team,
		'points': Point.objects.filter(player=player),
		'form': form_class,
	}
	return render(request, 'players/index.html', context)

@login_required
def add_point(request, player_id):
	form_class = PointForm
	player = get_object_or_404(UserPlayer, pk=player_id)

	if request.method == "POST":
		form = form_class(request.POST, request.FILES)

		if form.is_valid():
			point = form.save(commit=False)
			point.player = player
			point.point_owner = request.user
			point.team = str(player.player_team)
			point.save()
			player.points_scored += point.point
			player.save()
			player.player_team.team_points += point.point
			player.player_team.save()

			build_and_send_email_alert(player, point)

			try:
				number = PhoneNumber.objects.get(user=player.player_team.team_owner)
				if number.is_valid_phone_number:
					message = str(player) + ": received " + str(point) + " point(s)"
					send_sms(number, message)
			except:
				pass
		else:
			return render(request, 'players/index.html', {
				'player': player,
				'team': player.player_team,
				'points': Point.objects.filter(player=player),
				'form': form_class,
				'error_message': "Note is required",
			})

	context = {
		'player': player,
		'team': player.player_team,
		'points': Point.objects.filter(player=player),
		'form': form_class,
	}
	return HttpResponseRedirect(reverse('cloud_roni:players', args=(player.player_team.id, player.id)))

@login_required
def create_player(request, team_id):
	team = get_object_or_404(Team, pk=team_id)
	form_class = UserPlayerForm
	error_message = ''

	if not League.objects.get(participants=request.user).drafted:
		error_message = 'Your league has not drafted yet!'

	if request.method == 'POST' and League.objects.get(participants=request.user).drafted:
		form = form_class(request.POST, request.FILES)

		if form.is_valid():
			new_player = form.save(commit=False)
			new_player.player_team = team
			new_player.league = team.league
			new_player.save()
			return HttpResponseRedirect(reverse('cloud_roni:team', args= (team.id,)))
		else:
			error_message = "Form is invalid!"
			return render(request, 'players/create.html', {
					'form': form_class,
					'team': team,
					'error_message': error_message,
				})

	return render(request, 'players/create.html', {
				'form': form_class,
				'team': team,
				'error_message': error_message
				})

@login_required
def create_team(request):
	if request.method == 'POST':
		form = TeamForm(request.user, request.POST)
		if form.is_valid():
			new_team = form.save(commit=False)
			new_team.created_date = timezone.now()
			new_team.league = League.objects.get(participants=request.user)
			new_team = form.save()

			return HttpResponseRedirect(reverse('cloud_roni:index'))
		else:
			form_class = TeamForm(request.user)
			return render(request, 'teams/create.html', {
					'form': form_class,
					'error_message': "Invalid Information!",
				})

	form_class = TeamForm(request.user)
	return render(request, 'teams/create.html', {
				'form': form_class,
				})

@login_required
def update_player(request, player_id):
	player = get_object_or_404(UserPlayer, id=player_id)
	form = UserPlayerForm(request.POST or None, instance=player)

	if form.is_valid():
		form.save()
		context = {
			'player': player,
			'team': player.player_team,
			'points': Point.objects.filter(player=player),
			'form': PointForm,
		}
		return render(request, 'players/index.html', context)

	return render(request, 'players/update.html', {'form': form, 'team': player.player_team})

@login_required
@csrf_exempt
def place_trade(request, team_id):
	requesting_team = get_object_or_404(Team, team_owner=request.user)
	receiving_team = get_object_or_404(Team, id=team_id)

	if request.method == 'POST':
		new_trade = Trade(proposing_team=requesting_team,
						receiving_team=receiving_team,
						created_date=timezone.now(),)
		new_trade.save()
		for player_id in request.POST.getlist('requesting_team_ids[]'):
			player = UserPlayer.objects.get(id=player_id)
			new_trade.proposing_team_players.add(player)
		for player_id in request.POST.getlist('receiving_team_ids[]'):
			player = UserPlayer.objects.get(id=player_id)
			new_trade.receiving_team_players.add(player)

		try:
			number = PhoneNumber.objects.get(user=receiving_team.team_owner)
			if number.is_valid_phone_number:
				message = "A trade has been received by " + str(requesting_team)
				send_sms(number, message)
		except:
			pass
		new_trade.save()


		return JsonResponse({'trade': str(new_trade)})
	
	return render(request, 'teams/trade.html', {'requesting_team': requesting_team, 'receiving_team': receiving_team})

@login_required
@csrf_exempt
def complete_trade(request):
	trade = get_object_or_404(Trade, id=request.POST.get('trade_id'))
	outcome = request.POST.get('outcome')

	trade.update_outcome(outcome)

	try:
		number = PhoneNumber.objects.get(user=trade.proposing_team.team_owner)
		if number.is_valid_phone_number:
			message = str(trade.receiving_team) + " has " + trade.outcome.lower() + " your trade."
			send_sms(number, message)
	except:
		pass

	return JsonResponse({'outcome': trade.outcome})

@login_required
def delete_player(request, player_id):
	player = get_object_or_404(UserPlayer, pk=player_id)
	team = player.player_team
	player.delete()

	return HttpResponseRedirect(reverse('cloud_roni:team', args=(team.id,)))

def rules(request):
	return render(request, 'rules.html')

def build_and_send_email_alert(player, point):
	email_address = player.player_team.team_owner.email

	if email_address == '':
		return

	subject = str(player) + ' scored a point!'
	message = (str(point.point_owner) + ' has added a point for '
		+ str(player.player_first_name) + ' ' + str(player.player_last_name) + ': ' + str(point.point))

	send_mail(
	    subject,
	    message,
	    'cloud.roni.alerts@gmail.com',
	    [email_address],
	    fail_silently=False,
	)

def send_sms(to, message):
    client = Client(
        settings.TWILIO_ACCOUNT_SID, settings.TWILIO_AUTH_TOKEN)
    response = client.messages.create(
        body=message, to=to.twilio_formatted_number, from_=settings.TWILIO_NUMBER)
    return response

CloudRoni/templates/base.html
{% load static %}
{% load fontawesome %}
{% fontawesome_stylesheet %}
{% load debug %}

<script src="{% static 'CloudRoni/js/vendor/jquery/jquery.js' %}"></script>
<script src="{% static 'CloudRoni/js/base.js' %}"></script>
<link rel="stylesheet" href="{% static 'CloudRoni/css/base.css' %}">
<link rel="stylesheet" href="{% static 'CloudRoni/css/table.css' %}">

{% if user.participants.last.ended %}
    <div id='pop-up-container'>
        <div class='pop-up'>
            {% if user.league %}
                {% include "leagues/_start_new_season.html" %}
            {% else %}
                <h3>Your Season has ended...</h3>
                <p>
                    The League owner will need to start another season or a draft needs to occur.
                </p>
            {% endif %}
        </div>
    </div>
{% endif %}
<div id='nav-bar'>
    <div id='left-nav-bar'>
        <div id='main-logo' class='image-container'>
            <img src="{% static 'CloudRoni/img/logo_small.png' %}">
        </div>
        <a href="{% url 'cloud_roni:index' %}"><span class='nav-item'>Teams<span></a>
        <a href="{% url 'cloud_roni:all_players' %}"><span class='nav-item'>Players<span></a>
        <a href="{% url 'cloud_roni:my_trades' %}"><span class='nav-item'>My Trades<span></a>
        <a href="{% url 'leagues:past_seasons' %}"><span class='nav-item'>Past Season<span></a>
        {% if user.league %}
            <a href="{% url 'leagues:manage_league' %}"><span class='nav-item'>League Management</span></a>
        {% endif %}
    </div>
    
    

    <div id='right-nav-bar' class='login'>
        <form id="search-form" action="{% url 'cloud_roni:all_players' %}" method="get" accept-charset="utf-8">
            <input class="search-field" id="searchbox" name="q" type="text" placeholder="Search Players">
            <button class="search-button" type="submit">
                <i class="fa fa-search"></i>
            </button>
        </form>
    {% if user.participants.last.drafted %}
        <a style='float:left;' href="{% url 'drafts:draft_results' %}"><span class='nav-item'>Draft Results</span></a>
    {% endif %}
    {% if user.is_authenticated %}
        <a href="{% url 'users:logout' %}"><span class='nav-item'>Log out</span></a>
        <span>Hello, <a href="{% url 'users:account' user.id %}">{{ user.username }}</a></span>
    {% else %}
        <a href="{% url 'users:login' %}"><span class='nav-item'>Log in</span></a>
        <a href="{% url 'users:register' %}"><span class='nav-item'>Register</span></a>
    {% endif %}
    </div>
</div>

{% if user.email == '' %}
<p class='add-info-alert'>
    <strong>Add an <a href="{% url 'users:account' user.id %}">email</a> to receive email notifications</strong>
<p>
{% endif %}
{% if user.phonenumber.is_valid_phone_number == False %}
<p class='add-info-alert'>
    <strong>Add a <a href="{% url 'users:create_or_update_phone_number' %}">valid phone number</a> to receive text notifications</strong>
</p>
{% endif %}

<div id='body' style='margin-top: 25px;'>
{% block content %}{% endblock content %}
</div>

<div id='footer'>
</div>

<div id='powered-by' class='image-container'>
    <a href="{% url 'cloud_roni:rules' %}">Rules</a>
    <span>&middot;</span>
    <img id='power-by-logo' src="{% static 'CloudRoni/img/power_by_logo.png' %}">
</div>

CloudRoni/templates/rules.html
{% extends request.user.is_authenticated|yesno:"base.html,home_page_base.html" %}
{% load static %}
{% load fontawesome %}
{% debug %}

{% block content %}
<link rel="stylesheet" href="{% static 'CloudRoni/css/team.css' %}">
<div id='rules-container'>    
    <h1>CloudRoni Rules</h1>
    <h3>GOAL</h3>
    <p>
        The objective of this competition is to boost moral and create camaraderie. The other primary goal is to increase usership of your particular products and provide a means to get problematic clients to a level of self-sufficiency while increasing every day usage.
    </p>
    <h3>The Draft</h3>
    <p>
        Before the draft being the owner of the league will be required to upload a csv file of player that will be selected from and the necessary requirements for 
        said csv are provided at the upload page.
    </p>
    <h5>DRAFT RULES</h5>
    <p>
        The season will begin with a draft. The draft order will be determined by either randomized. During the draft there is will be a 3 minute long timer that the person currently set to pick will have to choose their client.
    </p>
    <h3>Trades</h3>
    <p>
        The option to trade players will be given to the teams and will exist in three states; Pending, Declined, and Accepted. Each team will be able to see all trades 
        that they are apart of their "Trades" tab.
    </p>
    <h3>Points</h3>
    <p>
        The point system could sometimes rely on an honor code system. In this event, if ever discovered that the team was caught not marking points they will immediately be given 10 points per discovered incident. 
        Also, in other cases it will be on the individual trainer who handled the client to mark points on the other team’s score. 
        Calls/Support Emails must be customer service related, if it is questionable, then trainers will vote and majority wins. 
        In the case of a tie, one trainer from opposing sides will play a sudden death game of Jenga (or your board game of choice).
    </p>
    <h3>How Do You Add Points:</h3>
    <ol>
        <li>One of the clients on your team calls into the office and speaks with a customer service representative:  +1</li>
        <li>The client call lasts 10 minutes or longer on the phone: +1</li>
        <li>A scheduled phone call(meeting) lasts longer than 1 hour: +1</li>
        <li>Missing a schedules call(meeting): +1</li>
        <li>Support email: +1</li>
        <li>Follow up requests for updates when client reports a bug: +1</li>
    </ol>
    <h3>How Do You Subtract Points:</h3>
    <ol>
        <li>When a client moves from lower usage to a higher usage: Each one is -5 (EX: from “Not Using” to “High” would -20 points)</li>
        <li>Attends a reschedule refresher: -1</li>
        <li>One of the clients on your team schedules a refresher training: -1</li>
    </ol>
    <p>
        *No Points If a client calls into cancel you must swap out our client for another client and can be added via the team's page.
    </p>
    <h3>Winning</h3>
    <p>
        The winner of the season will be determined by the team with the least amount of points in the end. Subsequently the loser will have the most and have to carry the most shame for being the worst. Nana Nana Boo Boo Stick Your Head In Doo Doo. All prizes (if any) will be determined on a season to season basis.
    </p>
    <h3>Usage</h3>
    <p>
        Usage should be determined based on actionable events that they perform on the given product. For example, if your particular product includes making phone calls
        then when a call is placed this would be one actionable event. Automatically triggered events should not count.
    </p>
    <h5>How Do You Determine Usage:</h5>
    <p>
        Usage is determined by the points added in the usage report excluding overdue tasks. Use the legend below.
    </p>
    <ul>
        <li>High >= 450</li>
        <li>Moderate >= 250</li>
        <li>Low >= 10</li>
        <li>Not Using below 10</li>
    </ul>
</div>
{% endblock content %}