cloud_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('leagues.urls', namespace='leagues')),
    url(r'cloud_roni/', include('CloudRoni.urls', namespace='cloud_roni')),
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^csv/', include('csv_upload.urls', namespace='csv_upload')),
    url(r'^draft/', include('drafts.urls', namespace='drafts')),    
]

csv_upload/urls.py
from django.conf.urls import url

from . import views

app_name = 'csv_upload'
urlpatterns = [
    url(r'^(?P<team_id>[0-9]+)/upload/csv/$', views.upload_csv, name='upload_csv'),
    url(r'^upload/csv/$', views.admin_upload_csv, name='admin_upload_csv'),
]

drafts/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

from . import views

app_name = 'drafts'
urlpatterns = [
    url(r'^start_draft/$', views.start_draft, name='start_draft'),
    url(r'^draft_player/$', views.draft_player, name='draft_player'),
    url(r'^end_draft/$', views.end_draft, name='end_draft'),
    url(r'^auto_draft/$', views.auto_draft, name='auto_draft'),
    url(r'^draft_results/$', views.draft_results, name='draft_results'),
]

leagues/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

from . import views

app_name = 'league'
urlpatterns = [
    url(r'^$', views.home_page, name='home_page'),
    url(r'^create_league/$', views.create_league, name='create_league'),
    url(r'^leagues/$', views.LeaguesListView.as_view(), name='leagues_index'),
    url(r'^join_league/$', views.join_league, name='join_league'),
    url(r'^manage_league/$', views.manage_league, name='manage_league'),
    url(r'^start_new_season/$', views.start_new_season, name='start_new_season'),
    url(r'^terminate_season/$', views.terminate_season, name='terminate_season'),
    url(r'^past_seasons/$', views.PastSeasonListView.as_view(), name='past_seasons'),
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

app_name = 'users'
urlpatterns = [
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^(?P<user_id>[0-9]+)/account/$', views.update_account, name='account'),
    url(r'^update_phone_number/$', views.create_or_update_phone_number, name='create_or_update_phone_number'),
]

leagues/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.apps import apps
import pdb
# Create your models here.

class League(models.Model):
    name = models.CharField(max_length=200)
    owner = models.OneToOneField(User)
    participants = models.ManyToManyField(User, related_name='participants')
    created_date = models.DateTimeField('date created')
    signup_code = models.CharField(max_length=15, unique=True, blank=False)
    end_date = models.DateTimeField(null=True, blank=True)
    ended = models.BooleanField(default=False)
    drafted = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def is_players_available(self):
        Team = apps.get_model('CloudRoni', 'Team')
        team_player_count = 0
        for team in Team.objects.filter(league=self):
            team_player_count += team.get_player_set().count()

        return team_player_count == self.league_player_count()

    def league_player_count(self):
        UserPlayer = apps.get_model('CloudRoni', 'UserPlayer')
        return UserPlayer.objects.filter(league=self).count()

class Winner(models.Model):
    individual = models.CharField(max_length=200)
    team_name = models.CharField(max_length=200)
    total_points = models.IntegerField(default=0)

class Season(models.Model):
    first = models.ForeignKey(Winner, related_name='first')
    second = models.ForeignKey(Winner, related_name='second')
    third = models.ForeignKey(Winner, related_name='third')
    league = models.ForeignKey(League)

leagues/forms.py
from django import forms
from leagues.models import League
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime
import pdb

class LeagueForm(ModelForm):
	end_date = forms.DateField(widget=forms.SelectDateWidget())
	
	def clean_end_date(self):
		data = self.cleaned_data['end_date']

		#Check date is not in past. 
		if data < datetime.date.today():
			raise ValidationError(_('Invalid date - date is in the past'))

		#Check date is in range librarian allowed to change (+4 weeks).
		if data < datetime.date.today() + datetime.timedelta(weeks=1):
			raise ValidationError(_('Invalid date - league time is too short (1 week or more)'))

		# Remember to always return the cleaned data.
		return data

	class Meta:
		model = League
		exclude = ['created_date', 'participants', 'owner', 'ended', 'drafted']

leagues/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponseNotFound
from leagues.forms import LeagueForm
from leagues.models import League, Winner, Season
from django.utils import timezone
from django.http import Http404, HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, render, redirect, render_to_response
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.views import generic
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from CloudRoni.models import Team, UserPlayer
from cloud_project.settings import TIME_ZONE
import dateutil.parser
import datetime
import pytz

import pdb

# Create your views here.
@csrf_exempt
def start_new_season(request):
	end_date = dateutil.parser.parse(request.POST.get('date'))
	end_date = pytz.timezone(TIME_ZONE).localize(end_date, is_dst=None)
	if end_date.date() < datetime.date.today() or end_date.date() < datetime.date.today() + datetime.timedelta(weeks=1):
		response = HttpResponse('Invalid Date - Select a date one week or more in the future')
		response.status_code = 500
		return response
	else:
		league = request.user.league
		league.end_date = end_date
		league.ended = False
		league.drafted = False
		league.save()
		return JsonResponse({'url': reverse('cloud_roni:index')})

def create_league(request):
	form_class = LeagueForm

	if request.method == 'POST':
		form = form_class(request.POST, request.FILES)

		if form.is_valid():
			try:
				League.objects.get(owner=request.user)
				return render(request, 'leagues/create.html', {
					'form': form_class,
					'error_message': "You have already created a league.",
				})
			except:
				form.cleaned_data['end_date']
				new_league = form.save(commit=False)
				new_league.created_date = timezone.now()
				new_league.owner = request.user
				new_league.save()
				new_league.participants.add(request.user)
				new_league.save()
				return HttpResponseRedirect(reverse('cloud_roni:index'))
		else:
			return render(request, 'leagues/create.html', {
					'form': form_class,
					'error_message': "Invalid Information!",
				})

	return render(request, 'leagues/create.html', {'form': form_class,})

class LeaguesListView(generic.ListView):
	template_name = 'leagues/join.html'
	context_object_name = 'leagues_list'

	def get_queryset(self):
		"""Return all leagues ordered by created_date"""
		return League.objects.all().order_by('-created_date')

class PastSeasonListView(generic.ListView):
	template_name = 'leagues/past_seasons.html'
	context_object_name = 'past_season_list'

	def get_queryset(self):
		"""Return all season ordered by id"""
		try:
			results = Season.objects.filter(league=self.request.user.league).order_by('-id')
		except:
			results = None
		
		return results

@csrf_exempt
def join_league(request):
	league_code = request.POST.get('code')
	league = League.objects.get(pk=int(request.POST.get('league_id')))
	if league.signup_code == league_code:
		league.participants.add(request.user)
		league.save()
		return JsonResponse({'url': reverse('cloud_roni:index')})
	else:
		return HttpResponseNotFound('Incorrect League Code')

def home_page(request):
	if request.user.is_authenticated():
		try:
			League.objects.get(participants=request.user)
			return HttpResponseRedirect(reverse('cloud_roni:index'))
		except:
			return HttpResponseRedirect(reverse('leagues:leagues_index'))

	register_form_class = UserCreationForm
	
	return render(request, 'leagues/home_page.html', {'form': register_form_class,})

@login_required
def manage_league(request):
	form = LeagueForm(request.POST or None, instance=request.user.league)
	confirmation = ''

	if request.method == "POST" and form.is_valid():
		confirmation = 'Updated League!'
		form.cleaned_data['end_date']
		form.save()

	return render(request, 'leagues/league_management.html', {'form': form, 'confirmation': confirmation})

def terminate_season(request):
	league = request.user.league
	
	#Requirement of three teams in a league
	if Team.objects.filter(league=league).count() < 3:
		form = LeagueForm(request.POST or None, instance=request.user.league)
		return render(request, 'leagues/league_management.html', {'form': form, 'confirmation': 'League is too small to terminate :('})
	end_season(league)
	return HttpResponseRedirect(reverse('cloud_roni:index'))

def end_season(league):
	teams =  Team.objects.filter(league=league).order_by('-team_points').reverse()[:3]
	players = UserPlayer.objects.filter(player_team=teams)
	players.update(player_team=None, drafted_team=None, drafted=False)
	winner_dict = {}
	for idx, team in enumerate(teams):
		winner = Winner(individual=str(team.team_owner),
						team_name=str(team.team_name),
						total_points=team.team_points)
		winner.save()
		winner_dict[idx] = winner
		team.delete()

	season = Season(league=league,
					first=winner_dict[0],
					second=winner_dict[1],
					third=winner_dict[2])
	season.save()

	league.ended = True
	league.end_date = None
	league.save()

leagues/templates/leagues/_start_new_season.html
{% load static %}
{% load fontawesome %}
{% fontawesome_stylesheet %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="{% static 'leagues/js/leagues.js' %}"></script>
<script>
  $( function() {
    $( "#datepicker" ).datepicker();
  } );
  
  $(document).ready(function() {
      $("#start-season-button").on('click', function() {
        startNewSeason('{% url "leagues:start_new_season" %}', $(this).siblings()[$(this).siblings().length - 1].children[0].value);
      });
  });
  </script>

<h2>Start a New Season:</h2>
<p></p>
<span>Select End Date: <input type="text" id="datepicker"></span>
<button id='start-season-button' class='creation-button button'>Start Season</button>

leagues/templates/leagues/create.html
{% extends 'base.html' %}
{% load static %}
{% load fontawesome %}

{% block content%}
<link rel="stylesheet" href="{% static 'CloudRoni/css/team.css' %}">

<h1 class='create-header'>Create A League</h1>

{% if error_message %}<p style='text-align:center;'><strong>{{ error_message }}</strong></p>{% endif %}

<form role="form" class='create-form' action="" method="post">
	{% csrf_token %}
	{{ form.as_p }}
<button type="submit">Create</button>
</form>

{% endblock content %}

leagues/templates/leagues/home_page.html
{% extends 'home_page_base.html' %}
{% load static %}
{% load fontawesome %}

{% block content%}
<link rel="stylesheet" href="{% static 'leagues/css/leagues.css' %}">
<script src="{% static 'leagues/js/leagues.js' %}"></script>
{% if error_message %}<p style='text-align:center;'><strong>{{ error_message }}</strong></p>{% endif %}

<div id="welcome-header">
    <h1>Welcome to</h1>
    <img class='large-logo' src="{% static 'CloudRoni/img/logo.png' %}">
    <h1>CloudRoni</h1>
</div>

<div id="button-container">
    <button class='button' id='sign-up-button'>Sign Up</button>
    <a class='button a-link-button' id='sign-in-button' href="{% url 'users:login' %}">Sign In</a>
</div>

<div id='sign-up-container'>
    <h3>Sign Up</h3>
    <form role="form" class='create-user-form' action="{% url 'users:register' %}" method="post">
	    {% csrf_token %}
	    {{ form.as_p }}
    <button class='button' type="submit">Create</button>
    </form>
    <a class='button a-link-button' id='sign-in-button' href="{% url 'users:login' %}">Sign In</a>
</div>

{% endblock content %}

leagues/templates/leagues/join.html
{% extends 'home_page_base.html' %}
{% load static %}
{% load fontawesome %}

{% block content%}
<link rel="stylesheet" href="{% static 'leagues/css/leagues.css' %}">
<script src="{% static 'leagues/js/leagues.js' %}"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $(".join-league-button").on('click', function() {
            joinLeague('{% url "leagues:join_league" %}', $(this).data('league-id'), $(this).siblings()[0].value);
        });
    });
</script>

<div id='leagues-table'>
	<h1 class='page-header'>Join a Leagues</h1>
	<p></p>
	<a class='creation-button' href="{% url 'leagues:create_league' %}">{% fontawesome_icon 'plus-circle' %} Create New League</a>
	<table>
		<th>League Name</th>
		<th>League Owner</th>
		<th></th>
		{% for league in leagues_list %}
			<tr>
				<td>{{ forloop.counter }}. {{ league.name }}</td>
				<td>{{ league.owner }}</td>
				<td class='join-column'><input type='text'/><button class='join-league-button button' data-league-id='{{ league.id }}'>Join</button></td>
			</tr>
	    {% endfor %}
	</table>
</div>

{% endblock content %}

leagues/templates/leagues/league_management.html
{% extends 'base.html' %}
{% load static %}
{% load fontawesome %}
{% load debug %}

{% block content%}
<link rel="stylesheet" href="{% static 'leagues/css/leagues.css' %}">
<script src="{% static 'leagues/js/leagues.js' %}"></script>

{% if confirmation %}<p class='add-info-alert'>{{ confirmation }}</p>{% endif %}

<div id="league-manage-container">
    <h3>League Information</h3>
    <form role="form" class='league-manage-form' action="" method="post">
    	{% csrf_token %}
    	{{ form.as_p }}
        <div class='button-holder button-div-100' style="margin-bottom: 5px;">
        	<button class='button' name='submit'>Update</button>
        </div>
    </form>
    <a class='button a-link-button' style='width: 75px;height: 30px;' href="{% url 'leagues:terminate_season' %}">Terminate Season</a>
    {% if not request.user.league.drafted %}
        <a class='button a-link-button' style='width: 75px;margin-top: 5px;' href="{% url 'drafts:start_draft' %}">Start Draft</a>
        <a href="{% url 'csv_upload:admin_upload_csv' %}">Upload Players for the Draft</a>
    {% endif %}
</div>

{% endblock content %}

leagues/templates/leagues/past_seasons.html
{% extends 'base.html' %}
{% load static %}
{% load fontawesome %}

{% block content%}
<script src="{% static 'leagues/js/leagues.js' %}"></script>
<link rel="stylesheet" href="{% static 'leagues/css/leagues.css' %}">

<div id='past-season-table'>
	<h1 class='page-header'>Past Seasons</h1>
	{% if past_season_list %}
	<table>
		<th>Season Number</th>
		<th>Winners</th>
		{% for season in past_season_list %}
			<tr>
			    <td>Season No. {{ forloop.counter }}</td>
				<td>
				    <ol>
				        <li>{{ season.first.team_name }}({{ season.first.individual }}) - Points: {{ season.first.total_points }}</li>
				        <li>{{ season.second.team_name }}({{ season.second.individual }}) - Points: {{ season.second.total_points }}</li>
				        <li>{{ season.third.team_name }}({{ season.third.individual }}) - Points: {{ season.third.total_points }}</li>
				    </ol>
				</td>
			</tr>
		{% endfor %}
		
	{% else %}
		<p>There are no past seasons</p>
	{% endif %}
	</table>
</div>


{% endblock content %}